### ISSUE TITLE
`isMinHeap` method missing

### ISSUE THREAD

**Issue by heyTruth** [benknoble/Comp410-JUnit#11]
Hey, thanks for the test! But where is the isMinHeap method?

**Comment by benknoble** [comment]
Good catch

/cc @zburk  I think most of the uses of `isMinHeap` were in your tests?

**Comment by heyTruth** [comment]
Thanks for confirming it.

**Comment by benknoble** [comment]
np. A cursory glance through the code shows that is indeed missing

**Comment by zburk** [comment]
My bad. That function wasn't copied in. Opened a PR
