### ISSUE TITLE
A3 tests

### ISSUE THREAD

**Issue by benknoble** [benknoble/Comp410-JUnit#14]
I'm a little concerned that we have only 22 tests for A3... normally I'd write my own but this week has been rather difficult for me, but we had a lot more for previous assignments.

What do you guys think? Do we need more tests? If so, please add them 😄

/cc @zburk @cowtongue

**Comment by zburk** [comment]
I might try and write more tests this afternoon but not guarantees.

**Comment by benknoble** [comment]
Don't worry about it too much @zburk. At this point, I'm no longer sure it matters
