### ISSUE TITLE
Problem with the test

### ISSUE THREAD

**Issue by heyCarlH** [benknoble/Comp410-JUnit#19]
Hi, again thank you for your tests! I have tried to use it but find out that there is a serious error. The splayed result is not consistent with the powerpoint. I used the RunTests jar from last semester and got 100 points back. But with this test, every method requiring splay fails. Thanks again for the test and I hope this helps.

**Comment by benknoble** [comment]
Yeah I've noticed that; that's why it's in progress and not finished yet. I'm working on it. Thanks for the feedback!

**Comment by heyCarlH** [comment]
Thank you for taking my advice!

**Comment by benknoble** [comment]
@heyCarlH Now that this semester's RunTests.jar is available, I will be using it in addition to my tests, but I was curious as to how you got ahold of last semesters jar?

**Comment by heyCarlH** [comment]
I just changed the import to f16 because I found out that his webpage is redirecting us to last semester's assignment page.

**Comment by heyCarlH** [comment]
BTW, I tested the newest JUNIT you just uploaded and still have these failures: testRemoveTwoChildren, testFindMax, testFindMin, testHeightInsertOnly, testRemoveOneChild, testSizeInsertOnly, testHeightRemoveOneChild, testSizeRemove and testInsert.

**Comment by benknoble** [comment]
@heyCarlH I do not have those errors when testing on code from the [a4-dev](https://github.com/benknoble/Comp410-JUnit/tree/a4-dev) branch, and I got a green light from all 16 of my tests and the Test jar

**Comment by heyCarlH** [comment]
I see. I will look into my code again. Thanks.

**Comment by heyCarlH** [comment]
Weird. I checked the code twice and it does not seem to have a problem. Maybe we did not rotate the tree as the same way?

**Comment by benknoble** [comment]
@heyCarlH 
It's certainly possible, but I don't see how. I used the powerpoint from class to implement the patterns and symmetries, and confirmed that with the animations.

One other potential is the remove: I use `left.findMax` in remove and while *technically* `right.findMin` would work, the description indicates that we should use `left.findMax`

**Comment by benknoble** [comment]
I will be taking a break to watch the game, but may intermittently check here for updates

**Comment by heyCarlH** [comment]
I did use left.finMax in my remove method. It is weird that I got containsTrue and containsFalse right but other methods using splay wrong.

**Comment by heyCarlH** [comment]
Hi, I checked the ppt again. In zig zig left and zig zig right, did you put G under P and 15 under ten? If so, could you please take a look to see if putting G under P and 10 under 15 instead is also correct?(like AVL tree) Many thanks.

**Comment by benknoble** [comment]
So, even though the powerpoint *says* it's an AVL double rotation, it's not. The Weiss text is actually very clear on this point: if we did only AVL rotations, we'd lose the efficiency of amortized complexity. I can find you a page number on that at some point, but I'd be very certain to just do what the powerpoint says, as that shouldn't be wrong. 

[I think this is correct. When I find the page I'm thinking of, I'll provide citational evidence].

**Comment by heyCarlH** [comment]
Thanks for the explanation. I have also asked on piazza and Max said that this is actually being debated. But they will not check that. They will only check if the root is correct, and if the tree meets the requirement of BST. But again, thanks for the tests! Here is an edited version of the test. I used printInOrderRec() to print in order traversal of the tree for people to check it manually.

`package SPLT_A4;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.junit.Test;

public class SplayTreeTests {

	@Test
	public void treeEqualsValidation() {
		BST_Node expected = new BST_Node("a"), tree = new BST_Node("a");
		tree.left = new BST_Node("b", null, null, tree);
		tree.right = new BST_Node("c", null, null, tree);
		tree.left.left = new BST_Node("d", null, null, tree.left);
		tree.left.right = new BST_Node("e", null, null, tree.left);
		tree.right.left = new BST_Node("f", null, null, tree.right);
		tree.right.right = new BST_Node("g", null, null, tree.right);

		expected.left = new BST_Node("b", null, null, expected);
		expected.right = new BST_Node("c", null, null, expected);
		expected.left.left = new BST_Node("d", null, null, expected.left);
		expected.left.right = new BST_Node("e", null, null, expected.left);
		expected.right.left = new BST_Node("f", null, null, expected.right);
		expected.right.right = new BST_Node("g", null, null, expected.right);
		assertTrue("Should pass if the `treeEquals` method works",
				treeEquals(tree, expected));

		expected.right.right = new BST_Node("h", null, null, expected.right);
		assertFalse("Should pass if the `treeEquals` method works",
				treeEquals(tree, expected));
	}

	@Test
	public void testFindMin() {
		try {
			SPLT tree = new SPLT();

			tree.insert("gg");
			tree.insert("dd");
			tree.insert("ss");
			tree.insert("ee");
			tree.insert("cc");
			tree.insert("zz");
			tree.insert("gg");
			tree.insert("bb");
			tree.insert("ff");
			tree.insert("aa");

			BST_Node expected = new BST_Node("aa", null, null, null);
			BST_Node bb, ff, cc, ee, zz, gg;
			expected.right = bb = new BST_Node("bb", null, null, expected);
			bb.right = ff = new BST_Node("ff", null, null, bb);
			ff.left = cc = new BST_Node("cc", null, null, ff);
			cc.right = ee = new BST_Node("ee", null, null, cc);
			ee.left = new BST_Node("dd", null, null, ee);
			ff.right = gg = new BST_Node("gg", null, null, ff);
			gg.right = zz = new BST_Node("zz", null, null, gg);
			zz.left = new BST_Node("ss", null, null, zz);

			printInOrderRec(tree.getRoot());
			System.out.println();

			assertEquals("findMin returns wrong node", "aa", tree.findMin());
			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testFindMax() {
		try {
			SPLT tree = new SPLT();

			tree.insert("gg");
			tree.insert("dd");
			tree.insert("ss");
			tree.insert("ee");
			tree.insert("cc");
			tree.insert("zz");
			tree.insert("gg");
			tree.insert("bb");
			tree.insert("ff");
			tree.insert("aa");

			BST_Node expected = new BST_Node("zz", null, null, null);
			BST_Node bb, ff, cc, gg, ee;
			expected.left = bb = new BST_Node("bb", null, null, expected);
			bb.left = new BST_Node("aa", null, null, bb);
			bb.right = gg = new BST_Node("gg", null, null, bb);
			gg.right = new BST_Node("ss", null, null, gg);
			gg.left = ff = new BST_Node("ff", null, null, gg);
			ff.left = cc = new BST_Node("cc", null, null, ff);
			cc.right = ee = new BST_Node("ee", null, null, cc);
			ee.left = new BST_Node("dd", null, null, ee);

			assertEquals("findMax returns wrong node", "zz", tree.findMax());
			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testContainsTrue() {
		try {
			SPLT tree = new SPLT();

			tree.insert("gg");
			tree.insert("dd");
			tree.insert("ss");
			tree.insert("ee");
			tree.insert("cc");
			tree.insert("zz");
			tree.insert("gg");
			tree.insert("bb");
			tree.insert("ff");
			tree.insert("aa");

			BST_Node expected = new BST_Node("cc");
			BST_Node aa, ff, ee, zz, gg;
			expected.left = aa = new BST_Node("aa", null, null, expected);
			aa.right = new BST_Node("bb", null, null, aa);
			expected.right = ff = new BST_Node("ff", null, null, expected);
			ff.left = ee = new BST_Node("ee", null, null, ff);
			ee.left = new BST_Node("dd", null, null, ee);
			ff.right = gg = new BST_Node("gg", null, null, ff);
			gg.right = zz = new BST_Node("zz", null, null, gg);
			zz.left = new BST_Node("ss", null, null, zz);

			assertTrue("contains returns false", tree.contains("cc"));
			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testContainsFalse() {
		try {
			SPLT tree = new SPLT();

			tree.insert("gg");
			tree.insert("dd");
			tree.insert("ss");
			tree.insert("ee");
			tree.insert("cc");
			tree.insert("zz");
			tree.insert("gg");
			tree.insert("bb");
			tree.insert("ff");
			tree.insert("aa");

			BST_Node expected = new BST_Node("bb", null, null, null);
			BST_Node ff, cc, ee, zz, gg;
			expected.left = new BST_Node("aa", null, null, expected);
			expected.right = ff = new BST_Node("ff", null, null, expected);
			ff.left = cc = new BST_Node("cc", null, null, ff);
			cc.right = ee = new BST_Node("ee", null, null, cc);
			ee.left = new BST_Node("dd", null, null, ee);
			ff.right = gg = new BST_Node("gg", null, null, ff);
			gg.right = zz = new BST_Node("zz", null, null, gg);
			zz.left = new BST_Node("ss", null, null, zz);

			assertFalse("contains returns true", tree.contains("ad"));
			assertTrue("tree not splayed correctly",
					treeEquals(tree.getRoot(), expected));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testEmptyTrue() {
		try {
			SPLT tree = new SPLT();

			assertTrue("empty returns false", tree.empty());
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testEmptyFalse() {
		try {
			SPLT tree = new SPLT();

			tree.insert("h");

			assertFalse("empty returns true", tree.empty());
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testHeightInsertOnly() {
		try {
			SPLT tree = new SPLT();

			tree.insert("a");
			tree.insert("d");
			tree.insert("s");
			tree.insert("e");
			tree.insert("c");
			tree.insert("g");
			tree.insert("b");
			tree.insert("f");

			BST_Node expected = new BST_Node("f");
			BST_Node b, e, c, g;
			expected.left = b = new BST_Node("b", null, null, expected);
			b.left = new BST_Node("a", null, null, b);
			b.right = e = new BST_Node("e", null, null, b);
			e.left = c = new BST_Node("c", null, null, e);
			c.right = new BST_Node("d", null, null, c);
			expected.right = g = new BST_Node("g", null, null, expected);
			g.right = new BST_Node("s", null, null, g);

			assertEquals("height returned wrong height", 4, tree.height());
			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testHeightRemoveRoot() {
		try {
			SPLT tree = new SPLT();

			tree.insert("a");
			tree.insert("d");
			tree.insert("s");
			tree.insert("e");
			tree.insert("c");
			tree.insert("g");
			tree.insert("b");
			tree.insert("f");
			tree.remove("f");

			BST_Node expected = new BST_Node("e");
			BST_Node b, c, g;
			expected.left = b = new BST_Node("b", null, null, expected);
			b.left = new BST_Node("a", null, null, b);
			b.right = c = new BST_Node("c", null, null, b);
			c.right = new BST_Node("d", null, null, c);
			expected.right = g = new BST_Node("g", null, null, expected);
			g.right = new BST_Node("s", null, null, g);

			assertEquals("height returned wrong height", 3, tree.height());
			assertTrue("tree not splayed correctly",
					treeEquals(tree.getRoot(), expected));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testHeightRemoveOne() {
		try {
			SPLT tree = new SPLT();

			tree.insert("a");
			tree.insert("d");
			tree.insert("s");
			tree.insert("e");
			tree.insert("c");
			tree.insert("g");
			tree.insert("b");
			tree.insert("f");
			tree.remove("g");

			BST_Node expected = new BST_Node("f");
			BST_Node b, e, c;
			expected.left = b = new BST_Node("b", null, null, expected);
			b.left = new BST_Node("a", null, null, b);
			b.right = e = new BST_Node("e", null, null, b);
			e.left = c = new BST_Node("c", null, null, e);
			c.right = new BST_Node("d", null, null, c);
			expected.right = new BST_Node("s", null, null, expected);

			assertEquals("height returned wrong height", 4, tree.height());
			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testSizeInsertOnly() {
		try {
			SPLT tree = new SPLT();

			tree.insert("a");
			tree.insert("d");
			tree.insert("s");
			tree.insert("e");
			tree.insert("c");
			tree.insert("g");
			tree.insert("b");
			tree.insert("f");

			BST_Node expected = new BST_Node("f");
			BST_Node b, e, c, g;
			expected.left = b = new BST_Node("b", null, null, expected);
			b.left = new BST_Node("a", null, null, b);
			b.right = e = new BST_Node("e", null, null, b);
			e.left = c = new BST_Node("c", null, null, e);
			c.right = new BST_Node("d", null, null, c);
			expected.right = g = new BST_Node("g", null, null, expected);
			g.right = new BST_Node("s", null, null, g);

			assertEquals("size returned wrong size", 8, tree.size());
			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testSizeRemove() {
		try {
			SPLT tree = new SPLT();

			tree.insert("a");
			tree.insert("d");
			tree.insert("s");
			tree.insert("e");
			tree.insert("c");
			tree.insert("g");
			tree.insert("b");
			tree.insert("f");
			tree.remove("g");

			BST_Node expected = new BST_Node("f");
			BST_Node b, e, c;
			expected.left = b = new BST_Node("b", null, null, expected);
			b.left = new BST_Node("a", null, null, b);
			b.right = e = new BST_Node("e", null, null, b);
			e.left = c = new BST_Node("c", null, null, e);
			c.right = new BST_Node("d", null, null, c);
			expected.right = new BST_Node("s", null, null, expected);

			assertEquals("size returned wrong size", 7, tree.size());
			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testInsert() {
		try {
			SPLT tree = new SPLT();

			tree.insert("a");
			tree.insert("d");
			tree.insert("c");
			tree.insert("s");
			tree.insert("e");
			tree.insert("c");
			tree.insert("g");
			tree.insert("b");
			tree.insert("f");

			BST_Node expected = new BST_Node("f");
			BST_Node b, d, g;
			expected.right = g = new BST_Node("g", null, null, expected);
			g.right = new BST_Node("s", null, null, g);
			expected.left = d = new BST_Node("d", null, null, expected);
			d.right = new BST_Node("e", null, null, d);
			d.left = b = new BST_Node("b", null, null, d);
			b.left = new BST_Node("a", null, null, b);
			b.right = new BST_Node("c", null, null, b);

			assertEquals("inserted wrong node into spot", "s",
					tree.getRoot().right.right.getData());
			assertEquals("inserted wrong node into spot", "g",
					tree.getRoot().right.getData());
			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testRemoveTwo() {
		try {
			SPLT tree = new SPLT();

			tree.insert("a");
			tree.insert("d");
			tree.insert("s");
			tree.insert("e");
			tree.insert("c");
			tree.insert("g");
			tree.insert("b");
			tree.insert("f");
			tree.remove("e");

			BST_Node expected = new BST_Node("d");
			BST_Node c, b, f, g;
			expected.left = c = new BST_Node("c", null, null, expected);
			c.left = b = new BST_Node("b", null, null, c);
			b.left = new BST_Node("a", null, null, b);
			expected.right = f = new BST_Node("f", null, null, expected);
			f.right = g = new BST_Node("g", null, null, f);
			g.right = new BST_Node("s", null, null, g);

			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void testRemoveThree() {
		try {
			SPLT tree = new SPLT();

			tree.insert("a");
			tree.insert("d");
			tree.insert("s");
			tree.insert("e");
			tree.insert("c");
			tree.insert("g");
			tree.insert("b");
			tree.insert("f");
			tree.insert("w");
			tree.insert("z");
			tree.insert("y");
			tree.insert("u");
			tree.remove("b");

			BST_Node expected = new BST_Node("a");
			BST_Node u, f, e, c, s, w, y;
			expected.right = u = new BST_Node("u", null, null, expected);
			u.left = f = new BST_Node("f", null, null, u);
			f.left = e = new BST_Node("e", null, null, f);
			e.left = c = new BST_Node("c", null, null, e);
			c.right = new BST_Node("d", null, null, c);
			f.right = s = new BST_Node("s", null, null, f);
			s.left = new BST_Node("g", null, null, s);
			u.right = w = new BST_Node("w", null, null, u);
			w.right = y = new BST_Node("y", null, null, w);
			y.right = new BST_Node("z");

			assertTrue("tree not splayed correctly", tree.getRoot().getData()
					.equals(expected.getData()));
			printInOrderRec(tree.getRoot());
			System.out.println();
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

	@Test
	public void sizeMedium() {
		SPLT tree = new SPLT();
		tree.insert("a");
		tree.insert("b");
		tree.remove("a");
		assertEquals("size not correct", 1, tree.size());
	}

	private void printInOrderRec(BST_Node currRoot) {
		if (currRoot == null) {
			return;
		}
		printInOrderRec(currRoot.left);
		System.out.print(currRoot.getData() + ", ");
		printInOrderRec(currRoot.right);
	}
}`

**Comment by benknoble** [comment]
I appreciate help on this, but I'd rather modify the tests to check both possible expected trees rather than require manual inspection... unfortunately, I don't have a way to visualize easily the AVL rotations, and I think the splay rotations are better.

If Max said they're only checking the root, than I'll leave a note in the test suite explaining how to adjust the tests for AVL rotations

**Comment by heyCarlH** [comment]
Sure. Thanks for the help on this issue.
