### ISSUE TITLE
A possible bug

### ISSUE THREAD

**Issue by heyCarlH** [benknoble/Comp410-JUnit#22]
Assignment num

[Refs #] Brief description

**Comment by heyCarlH** [comment]
I am wondering why it is assertFalse

public void DeleteSingleEdgeTest() {
		try {
			DiGraph d = new DiGraph();
			d.addNode(0, "first");
			d.addNode(1, "second");
			d.addEdge(0, "first", "second", 1, "a");
			assertFalse("Deleting edge failed", d.delEdge("first", "second"));
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

**Comment by heyCarlH** [comment]
And there is another possible bug: why is this assertTrue? Shouldn't d.addEdge return false in this situation?

@Test
	public void AddSecondEdgeToSelfTest() {
		try {
			DiGraph d = new DiGraph();
			d.addNode(0, "a");
			d.addEdge(0, "a", "a", 1, null);
			assertTrue("Adding second edge from node to self succeeded", d.addEdge(1, "a", "a", 1, null));
		} catch (Exception e) {
			fail("Exception thrown: " + e.getMessage());
		}
	}

**Comment by benknoble** [comment]
For your first issue, you are correct. Fix is forthcoming.

For your second issue, you are correct. Fix is in most recent commit, I believe.

**Comment by heyCarlH** [comment]
Thank you very much.
