### ISSUE TITLE
Tests that need to be created

### ISSUE THREAD

**Issue by zburk** [benknoble/Comp410-JUnit#8]
1. Removing items on the left side of the tree
2. ~~Remove fail because item not found in tree~~

I'm putting these here for now but will hopefully get around to developing these tests. If someone has some free time or has already created these tests, comment to let me know before I put some time into developing them.

**Comment by benknoble** [comment]
What do you mean by removing items of the left side of the tree (1)? That's no different than any other remove, and my tests for that are fairly extensive. I can double check, but I'm sure there's at least one remove on the left side, probably several due those 400 random insert/removes

**Comment by zburk** [comment]
I designed my remove poorly so I'll be refactoring it tomorrow. I'll close this issue.
